sudo: required


language: python
python:
  -  "3.5"

services:
  - docker

script: true

install:
  - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/BaardBouvet-patch-1/after_success.sh)
